name: pileline
on: 
  push:
    branches:
      - master
jobs:
  pipeline:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: npm install
        run: npm install
      - name: npm lint
        run: npm run lint-fix
      - name: e2e tests
        uses: cypress-io/github-action@v2
        with: 
          start: npm run start
          wait-on: http://localhost:3000