

on:
  push:
    branches:
      - teststuff

jobs:
  a_test_job:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: gihub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: commits
        env:
          COMMITS: ${{ toJson(github.event.commits) }}
        run: echo "$COMMITS" && echo "$GITHUB_CONTEXT"
      - name: commit messages
        env:
          COMMIT_MESSAGES: ${{ toJson(github.event.commits.*.message) }}
        run: echo "$COMMIT_MESSAGES"
      - name: if!=push
        if: ${{ github.event_name != 'push' }}
        run: echo "if!=push"
      - name: if==push
        if: ${{ github.event_name != 'push' }}
        run: echo "if==push"